In [1]:
# import libraries
import pandas as pd
from datasets import load_dataset
import matplotlib.pyplot as plt

#load dataset
dataset = load_dataset('lukebarousse/data_jobs')
df = dataset['train'].to_pandas()

# data cleanup
df['job_posted_date'] = pd.to_datetime(df['job_posted_date'])

c:\Users\stuco\anaconda3\envs\python_course\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

In [3]:
df.loc[:10, 'salary_year_avg': 'salary_hour_avg']

    salary_year_avg  salary_hour_avg
0               NaN              NaN
1               NaN              NaN
2               NaN              NaN
3               NaN              NaN
4               NaN              NaN
5               NaN              NaN
6               NaN              NaN
7               NaN              NaN
8               NaN              NaN
9               NaN              NaN
10              NaN              NaN

In [6]:
median_salary_year = df['salary_year_avg'].median()

In [9]:
median_salary_hour = df['salary_hour_avg'].median()

In [12]:
# use fillna to replace NaN values with median value
# to be safe, we'll keep the original dataframe intact

df_filled = df

df_filled['salary_year_avg'] = df_filled['salary_year_avg'].fillna(median_salary_year)
df_filled['salary_hour_avg'] = df_filled['salary_hour_avg'].fillna(median_salary_hour)

In [13]:
df_filled.loc[:10, 'salary_year_avg':'salary_hour_avg']

    salary_year_avg  salary_hour_avg
0          115000.0            45.98
1          115000.0            45.98
2          115000.0            45.98
3          115000.0            45.98
4          115000.0            45.98
5          115000.0            45.98
6          115000.0            45.98
7          115000.0            45.98
8          115000.0            45.98
9          115000.0            45.98
10         115000.0            45.98

In [ ]:
# now lets drop the duplicate values

df_unique = df_filled

df_unique = df_unique.drop_duplicates() # this needs to be assinged a variable

# from the above line, we get the data w/ removed duplicates, but lets see how much we removed

print("Length of original df:       ", len(df_filled))
print("Length of drop duplicates df:", len(df_unique))
print("Rows Dropped:                ", len(df_filled) - len(df_unique))

Length of original df:        785741
Length of drop duplicates df: 785640
Rows Dropped:                 101

In [ ]:
# we're going to drop duplicates but now focusing on duplicates in the job_title, company name columns
df_unique = df_unique.drop_duplicates(subset=['job_title', 'company_name'])

print("Length of original df:       ", len(df_filled))
print("Length of drop duplicates df:", len(df_unique))
print("Rows Dropped:                ", len(df_filled) - len(df_unique))

Length of original df:        785741
Length of drop duplicates df: 508042
Rows Dropped:                 277699